### PR TITLE
Hotfix/0.5 all new

### PR DESCRIPTION
**Pull request by abea**
Previously the client JS removed siblings of the "New Page" button, but that missed any snippet types that aren't pages. The update makes this broader to capture those types.

### CODE REVIEW

**Comment by abea** [comment]
It might not be how we'd go about this today, but improves on the original.

**Comment by boutell** [comment]
Looks good. When releasing with npm publish make sure you tag it in npm with `--tag ohdotfive` (which sounds dumb, but you can't use anything that is also a valid semver range), so it doesn't get marked automatically with the "latest" tag and show up in npm as the latest version of workflow.

**Comment by boutell** [comment]
If it shows up ANYWAY though - npm's website has been buggy about this before - don't worry about it, just nudge me to publish my latest work in workflow which I'm gonna do today anyway (let's sequence this, yours then mine).

**Comment by abea** [comment]
Looks like it published smoothy 🏄‍♀️

**Pull request merged**
